// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  quote: defineAsyncComponent(() => import("./Quote/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
